# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../alluxio_client_install.yml
- ansible.builtin.import_playbook: ../alluxio_kerberos_install.yml
- ansible.builtin.import_playbook: ../alluxio_config.yml
- ansible.builtin.import_playbook: ../alluxio_client_config.yml
- ansible.builtin.import_playbook: ../alluxio_namenode_config.yml
- ansible.builtin.import_playbook: ../alluxio_datanode_config.yml
- ansible.builtin.import_playbook: ../alluxio_init_datanode.yml
- ansible.builtin.import_playbook: ../alluxio_init_namenode.yml
- ansible.builtin.import_playbook: ../alluxio_start.yml
# - ansible.builtin.import_playbook: ../alluxio_mount_hdfs.yml
- ansible.builtin.import_playbook: ../alluxio_mount_hdfs.yml
